gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

